apiVersion: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:8080
    database: ""
    isDefault: true
    editable: true
    jsonData:
      graphiteVersion: "1.1"
      keepCookies: []
    secureJsonFields: {}
    version: 1
