version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_dev
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://mysql:3306/ecommerce_dev?useSSL=false&serverTimezone=UTC
      DB_USERNAME: ecommerce_user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/target

volumes:
  mysql_dev_data:
